# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Zoybzo"
repo_name: "recsys-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/recsys-arxiv-daily.json'
json_gitpage_path: './docs/recsys-arxiv-daily-web.json'
json_wechat_path: './docs/recsys-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "RecSys":
        filters: ["recsys", "personalized", "multi-modal"]
    "LLM":
        filters: ["llm", "large language model", "finetuning", "pretrained"]
    "Image Genration":
        filters: ["image generation", "text to image", "image to image"]
